package com.example.bzaharic.nsguideapp;

import com.example.bzaharic.nsguideapp.database.MonumentDAOWrapper;
import com.example.bzaharic.nsguideapp.model.Monument;

import org.androidannotations.annotations.Bean;
import org.androidannotations.annotations.EBean;

/**
 * Created by bzaharic on 28.12.17..
 */
@EBean
public class UtilityDatabaseClass {

    @Bean
    MonumentDAOWrapper monumentDAOWrapper;

    Monument gradskaKuca = new Monument("Gradska kuća","http://novisad.travel/wp-content/uploads/2017/01/gradska-kuca2.jpg","GRADSKA KUĆA (Magistrat) na Trgu slobode je monumentalno neorenesansno zdanje izgrađeno 1895. Za podizanje Magistrata raspisan je 1855. konkurs na kome su mogli da učestvuju svi graditelji Hasburške monarhije. Posao je dobio baumeister Đerđ Molnar koji je izgradio zgradu Magistrata (Rathaus, Varoshaz) kao impresivnu građevinu sa četiri kupole na sva četiri ugla zgrada i tornjem na čijem vrhu se nalazi balkon. U vreme kada je zgrada nastala na vrhu tornja je postavljeno zvono za uzbunu u slučaju požara. Zvono, koje su Novosađani zvali „Matilda’’, pretopljeno je u ratno vreme, ali je sećanje na „Matildu’’ i danas živo. Najuočljiviji elementi fasade su alegorijske figure rad novosadskog vajara Julija Anike. Vajarska plastika inspirisana antičkom mitologijom predstavlja različite ljudske delatnosti, uvek u skladu sa visokim moralnim vrednostima. Danas je Gradska kuća sedište Gradonačelnika Novog Sada i odgovarajućih službi. U njoj se nalazi i Svečana sala koju je ukrasio slikar Pavle Ružička medaljonima u kojima su predstavljeni simboli poljoprivrednog , zanatskog i trgovačkog staleža.");
    Monument spomenikSM = new Monument("Spomenik Svetozaru Miletiću","http://novisad.travel/wp-content/uploads/2017/01/MileticDKMQ7A94221-1.jpg","SPOMENIK SVETOZARU MILETIĆU, najznačajnijem srpskom političaru u Vojvodini u 19. veku nalazi se na Trgu slobode. Bronzana statua visoka 5 m rad je slavnog hrvatskog vajara Ivana Meštrovića iz 1939. Tokom II svetskog rata spomenik je sklonjen da bi odmah po oslobođenju vraćen na mesto na kojem se i danas nalazi. Svetozar Miletić (1826-1901) je u istoriji zapamćen kao advokat i gradonačelnik Novog Sada (1861-1862; 1867-1868), poslanik ugarskog i hrvatskog sabora, predsednik Srpske čitaonice, jedan od osnivača Srpskog narodnog pozorišta (1861) ali i kao osnivač Srpske narodne slobodoumne stranke (1869) i pokretač lista Zastava (1866) jednog od najuticajnijih kod Srba u Habzburškoj monarhiji. Njegove ideje i politički program uticali su na kreiranje nacionalnog programa i nacionalnog pokreta vojvođanskih Srba u drugoj polovini 19. veka. Zbog svog političkog delovanja je više puta hapšen, osuđivan i zatvaran. Iz političkog života se povukao zbog bolesti nastale posle dugog tamnovanja. Umro je u Vršcu 1901.");
    Monument hotelV = new Monument("Hotel “Vojvodina”","http://novisad.travel/wp-content/uploads/2017/05/Hotel-Vojvodina-800x800.jpg","ZGRADA HOTELA „VOJVODINA’’ je više od jednog i po veka uvek bila hotel, samo su se kroz vekove i epohe menjali njegovi nazivi. Prvi hotel na ovom mestu sagradio je 1854. Johan Ajgler. Bila je to luksuzno opremljena pozno-klasicistička građevina. Nazvana je po carici Jelisaveti (Elizabeti) Austrijskoj, supruzi Franca Jozefa I. Hotel nazvan po carici Jelisaveta je bio mesto okupljanja više klase poznato po dobroj kuhinji, vinima, balovima i zabavama. Sledeći vlasnik je bio Gedeon Dunđerski. U dvorištu hotela je 1895. sazidano pozorište Lazara Dunđerskog po projektu arhitekte Vladimira Nikolića. Pozorište koje je imalo 650 mesta izgorelo je 1928. godine. Tada je nepovratno uništena biblioteka, garderoba, dekoracija i mnogi drugi predmeti Srpskog narodnog pozorišta koje je tu davalo predstave. Posle završetka Prvog svetskog rata hotel je nazvan po kraljici Mariji, supruzi kralja Aleksandra (Karađorđevića). Posle završetka Drugog svetskog rata hotel dobija današnji naziv – „Vojvodina’’. Tokom više od vek i po postojanja hotel su posetili ili u njemu boravili: Laza Kostić, Marko Miljanov, Miloš Crnjanski i druge ugledne ličnosti. U njemu je 1974. umro slavni mađarski književnik Lajoš Zilahi u čiju čast je nazvan prolaz koji spaja dvorište hotela i Ulicu kralja Aleksandra.");
    Monument rmkCrkva = new Monument("Rimokatolička Crkva Imena Marijinog","http://novisad.travel/wp-content/uploads/2017/05/Rimokatolicka_-crkva-_Ime_Marijino.jpg","Rimokatolička Crkva Imena Marijinog (poznata kao katedrala) je izgrađena u neogotskom stilu između 1893. i 1895. Sagrađena je na Trgu slobode na mestu starijih crkava od kojih je najstarija izgrađena u prvim decenijama 18. veka. Tokom Bune (1849) prvobitna crkva je bila zapaljena, a po okončanju ratnih sukoba katolička zajednica je započela obnovu svog hrama koji je od 1864. postao i stalni katedralni hram. Krajem 19. veka katolička zajednica Novog Sada je odlučila da sazida novi, reprezentativni hram koji i danas postoji. Krajem 1891. srušena je stara katolička crkva, a nova je početa da se zida po projektu baumeister-a Đerđa Molnara. On je sazidao trobrodnu baziliku sa tornjem visokim 73 m što je čini najvišom bogomljom u gradu. U crkvi se nalaze četiri oltara, a glavni krasi tirolska rezbarija. Prozori su ukrašeni vitražima, rađenim u Pešti, a na njima su predstavljene biblijske scene i grbovi znamenitih novosadskih katoličkih porodica. Crkva ima orgulje iz 1895. U njoj se danas organizuju prigodni koncerti među koje spadaju i koncerti uglednih orguljaša. Posle požara koji se desio 1904. crkva je obnovljena, a krov je ukrašen šestougaonim emajliranim keramičkim pločicama. Bista arhitekte baumeister-a Đerđa Molnara se nalazi u niši ispod hora crkve. Tokom najnovije obnove rađeno je na čišćenju žute fasadne cigle kojom je crkva prekrivena, a zatim je urađen projekat osvetljenja što je doprinelo da rimokatolička župna crkva Ime Marijino bude jedna od najprepoznatljivijih građevina u Novom Sadu.");
    Monument zgradaViSAPV = new Monument("Zgrada Vlada i Skupštine Autonomne pokrajine Vojvodine","http://novisad.travel/wp-content/uploads/2017/05/vlada-i-skupstina-autonomne-pokrajine-vojvodine-800x800.jpg","VLADA I SKUPŠTINA AUTONOMNE POKRAJINE VOJVODINE nalaze se u zgradi koja je poznata kao Banovina. Ova jedinstvena arhitektonska celina izgrađena je u periodu 1936-1940. po projektu jednog od naših najvećih arhitekata u Srbiji između dva svetska rata, Dragiše Brašovana (1887-1965). Njegov opus ne obuhvataju samo građevine u Novom Sadu i Vojvodini već i u Beogradu. Njegov ugled je bio izuzetan a dokaz je i to što je Brašovan bio autor jugoslovenskih paviljona na Svetskoj izložbi u Barseloni (1929) i Milanu (1931). Zgrada Banovine ili Banskog dvora sastoji se iz dve celine. U većoj zgradi se danas nalazi Vlada Vojvodine sa svim pratećim službama i sekretarijatima, a u manjoj je Skupština Autonomne pokrajine Vojvodine. Vrednost ove velelepne građevine povećava i to što je obložena bračkim mermerom, dok se u unutrašnjosti nalazi centralno stepenište za čiju izradu je korišćen i mermer iz Karare. U zgradi Vlade Vojvodine se nalazi vrlo vredna kolekcija slika jugoslovenskih autora nastala tokom 20. veka.  Stanovnici i posetioci Novog Sada mogli su da obiđu Banovinu tokom »Dana evropske baštine«");
    Monument maticaSrpska = new Monument("Matica srpska","http://novisad.travel/wp-content/uploads/2017/05/matica-srpska-800x800.jpg","MATICA SRPSKA je najstarija i najuglednija kulturna i naučna institucija kod Srba. Osnovana 1826. u Budimpešti, u Novi Sad je preseljena 1864. Osnivači Matice srpske: Jovan Hadžić, Petar Rajić, Andrija Rozmirović, Gavrilo Bozitovac, Jovan Demetrović, Josif Milovuk i Đorđe Stanković okupili su se oko ideje očuvanja srpske kulture i tradicije, njenog predstavljanja drugim narodima u Evropi i podizanja opšteg kulturnog nivoa srpskog naroda. Zbog toga je izdavačka delatnost bila jedna od najznačajnijih delatnosti o čemu svedoči i postojanje „Letopisa Matice srpske’’, najstarijeg književnog časopisa na svetu koji u kontinuitetu izlazi od 1824. U sastavu Matice srpske su Biblioteka i Galerija Matice srpske. Zgrada Matice srpske izgrađena je 1912. novcem Marije Trandafil, po projektu Momčila Tapavice, a useljena je 1928. U zgradi se danas nalazi sedište Matice srpske, Biblioteka, i odeljenja za: književnost i jezik, prirodne nauke, društvene nauke, likovne umetnosti, scenske umetnosti i muziku, Leksikografsko odeljenje i  Rukopisno odeljenje Matice srpske. Tu se čuva i vrlo vredna kolekcija portreta osnivača, dobrotvora i darodavaca Matice srpske koju su radili vodeći srpski slikari, pretežno tokom 19. veka.");
    Monument gimnazijaJJZ = new Monument("Gimnazija „ Jovan Jovanović Zmaj’’","http://novisad.travel/wp-content/uploads/2017/05/Gimnazija_Jovan_Jovanovic_Zmaj_2-800x800.jpg","ZGRADA GIMNAZIJE „ JOVAN JOVANOVIć ZMAJ’’ izgrađena je u duhu eklekticizma na mestu gde se od druge polovine 18. veka nalazila Srpska pravoslavna velika gimnazija. Projekat za zgradu napravio je jedan od najpoznatijih srpskih arhitekata s kraja 19. i početkom 20. veka Vladimir Nikolić, poznat i kao graditelj značajnih objekata u Sremskim Karlovcima (Patrijaršijski dvor, Bogoslovski seminar, zgrada Crkveno-narodnih fondova – Bogoslovija, Stefaneum). Osnova zgrade Gimnazije podseća na osnovu Patrijaršijskog dvora u Sremskim Karlovcima jer je projektovana u obliku ćiriličnog slova П sa glavnom fasadom koja se sastoji od tri rizalita sa kupolama. Neorenesansna zgrada Gimnazije ima dva velika dvorišta. Enterijer je prilagođen nameni objekta, a lepotom se ističe Svečana sala čiji si zidovi i tavanica bogato ukrašene. Gradnju zgrade Gimnazije je finansirao veleposednik, poslanik ugarskog sabora baron Miloš Bajić, a o tome obeveštava i natpis iznad ulaza u zgradu: „Baron Miloš Bajić srpskom narodu’’. Na zidu Gimnazije na početku ulice Zlatne grede nalazi se tabla koja obaveštava da se na tom mestu nalazila kuća u kojoj je rođen lekar, pesnik, prevodilac, ugledni član Matice srpske i Srpske kraljevske akademije, Jovan Jovanović Zmaj (1833-1904).");
    Monument ulicaDunavska = new Monument("Ulica Dunavska","http://novisad.travel/wp-content/uploads/2017/05/dunavska-ulica-800x800.jpg","DUNAVSKA ULICA je jedna od najstarijih u Novom Sadu, spaja obalu Dunava i Zmaj Jovinu ulicu. Njen današnji izgled je rezultat obnove koja je otpočela sredinom 19. veka posle velikih razaranja u Buni 1849. Gusto zbijene jednospratnice u prvom delu ulice kriju razgranatu mrežu pasaža u kojima su prodavnice, restorani, poslastičarnice. Na početku ulice nalazi se Gradska biblioteka – zadužbina Anke i Arse Pajević. Preko puta je najstarija kuća u Novom Sadu – „Kod belog lava’’ sagrađena u prvim decenijama 18. veka. To je jedna od retkih građevina koja nije srušena u Buni. U pasažu zgrade skriven je mehanizam koji je pripadao bunaru iz koga su se stanovnici snabdevali vodom iz Dunava. Na broju 14. živeo je Svetozar Miletić, srpski političar i gradonačelnik Novog Sada, a nešto niže na istoj strani čuvene glumice srpskog glumišta Sofija Vujić i njena kći, glumica i rediteljka Milka Marković. Sa druge strane ulice na broju 29. je Zbirka strane umetnosti, depandans Muzeja Grada Novog Sada gde posetioci mogu videti umetnička dela nastala u Evropi u rasponu od 15. do 20. veka. Ispred Zbirke je spomenik srpskom političaru Jaši Tomiću (1856-1922). U produžetku ulice nalaze se zgrade Muzeja Vojvodine (35-37) i Muzeja savremene umetnosti Vojvodine (37).");
    Monument vladicanskiDvor = new Monument("Vladičanski dvor","http://novisad.travel/wp-content/uploads/2017/05/Vladicanski_Dvor.jpg","VLADIČANSKI  DVOR  Eparhije bačke Srpske pravoslavne crkve se uvek nalazio na raskrsnici Zmaj Jovine i Dunavske ulice, u neposrednoj blizini pravoslavnog , sabornog hrama сv. Đorđa. Zgrada starog Dvora, izgrađena 1741. zalaganjem vladike Visariona Pavlovića, porušena je tokom bombardovanja Novog Sada sa Petrovaradinske tvrđave u Buni 1849. Projekat za novu zgradu uradio je arhitekta Vladimir Nikolić 1899. a gradnja je okončana 1901. Vladičanski dvor je markantna, reprezentativna građevina izgrađena u eklektičkom stilu mešavinom romantizma i secesije a poseban, neponovljiv utisak daju joj dekorativni elementi fasade bifore i trifore i obilje fasadnih ukrasa. Taj utisak je pojačan upotrebom crvene fasadne opeke kojom je zgrada obložena. Na fasadi Dvora se nalazi i grb Eparhije bačke. Enterijer Dvora izveden je s velikom pažnjom, a prema načinu izrade ističu se stepenište sa ogradom od kovanog gvožđa i oslikana dvorska trpezarija, rad Vladimira Predojevića. Unutar Dvora postoji i kapela čiji je ikonostas radio Vladimir Kuročkin. Regent Aleksandar Karađor- đević je tokom posete Novom Sadu 1919. boravio u Dvoru i sa balkona se obratio okupljenim građanima.");
    Monument zgradaCetKredZavoda = new Monument("Zgrada Centralnog kreditnog zavoda","http://novisad.travel/wp-content/uploads/2017/05/Zgrada_Centralnog_kreditnog_zavoda-800x800.jpg","ZGRADA CENTRALNOG KREDITNOG ZAVODA nalazi se na uglu ulica Miletićeve i Grčkoškolske. Zgrada u stilu akademizma bogate dekoracije projektovao je bečki arhitekta češkog porekla, Franc Voruda. Izgrađena je 1895. a među graditeljima se može naći i ime Đerđa Molnara. U vreme gradnje zgrada je bila vlasništvo Centralnog Kreditnog Zavoda u Novom Sadu koji je uz Srpsku banku d.d. u Zagrebu bio najznačajnija finansijska institucija Srba u Habzburškoj monarhiji. Centralni Kreditni Zavod je osnovan 1890. kao deoničarsko društvo sa ciljem da pomaže trgovačke, zanatske, ekonomske interese kao i prosvetnu i kulturnu delatnost Srba u Hrvatskoj i Ugarskoj. Prvobitno zgrada je imala samo jedan sprat ali je 1925. podignut još jedan sprat, opet prema projektu Franca Vorude. Najupečatljiviji utisak ostavlja ulaz u zgradu iznad koga se diže kupola na čijem vrhu je skulptura Merkura, u rimskoj mitologiji boga zaštitnika trgovaca i trgovine. Skulptura je rad vajara Đorđa Jovanovića. Zgrada ima bogatu dekoraciju rađenu pod uticajem secesije.");
    Monument kultCentNS = new Monument("Kulturni centar Novog Sada","http://novisad.travel/wp-content/uploads/2017/05/Kulturni_centar_Novi_Sad-800x800.jpg","KULTURNI CENTAR NOVOG SADA je institucija kulture sa tradicijom dužom od pola veka. Pedesetih godina 20. veka su kao preteče savremenog Kulturnog centra u Novom Sadu delovale Tribina mladih i Kulturni centar mladih „Sonja Marinković” kao institucije koje su okupljale najznačajnija imena iz sveta umetnosti, a naročito književnosti, u socijalističkoj Jugoslaviji. O tome od 1955. sa manjim prekidima svedoči časopis za književnost i teoriju „Polja”, kao svojevrsni pregled različitih književnih estetika u regionu širem od prostora socijalističke Jugoslavije. Savremeni Kulturni centar Novog Sada je institucija kulture koja neguje različite programe – od likovnih do muzičkih, od pozorišnih do filmskih i književnih, a većina se dešava u sledećim prostorima: Klub „Tribina mladih”, velika sala KCNS, Likovni salon KCNS i Mali Likovni salon KCNS. Kulturni centar Novog Sada organizuje sledeće, tradicionalne festivale: INFANT – Internacionalni festival alternativnog i novog teatra, Novosadski džez festival, Prosefest, Festival evropskog i nezavisnog filma- Euro In Film, Festival Antićevi dani i druge.");
    Monument zgradaRMKZU = new Monument("Zgrada Rimokatoličkog župnog ureda – Plebanija","http://novisad.travel/wp-content/uploads/2017/05/porta-800x420.jpg","ZGRADA RIMOKATOLIČKOG ŽUPNOG UREDA – PLEBANIJE jedna je od retkih građevina koje su ostale netaknute u vreme Bune kada je 1849. Novi Sad bombardovan topovima sa Petrovaradinske tvrđave. Zgrada je izgrađena 1808. prema planu koji je uradio Georg Efinger. Spada u retke primere arhitekture koja poseduje odlike klasicizma i kasnog baroka. Simetričnost glavne fasade rešena je plitkim centralnim rizalitom sa četiri pilastra, krovnim vencem sa plastičnim ukrasom i simetrično postavljenim pravougaonim prozorima. Na zgradi je uočljiv krov građen u maniru baroknih krovova na četiri vode i visoko postavljen. U unutrašnjosti se nalazi bogato dekorisana Svečana dvorana.");
    Monument zgradaVBanke = new Monument("Zgrada Vojvođanske banke","http://novisad.travel/wp-content/uploads/2017/05/Zgrada_Vojvodjanske_banke-1-800x800.jpg","ZGRADA VOJVOĐANSKE BANKE (Trg slobode) je poznata i kao nekadašnji Dom JNA. U istorijskim izvorima se može naći da je na ovom mestu 1754. postojala spratna građevina poznata kao kafana „Kod Zelenog venca’’, vlasništvo kapetana Save Nikolića. Vlasnici kafane, a kasnije hotela „Zeleni venac’’, često su se menjali sve do kraja 19. veka kada je građevina srušena. Sredinom 19. veka hotel „Zeleni venac’’ je bio mesto susreta i vatrenih poli- tičkih rasprava gradske više klase i pristalica političkog programa Svetozara Miletića. Pred kraj 19. veka hotel „Zeleni venac’’ je izgubio sjaj i uglednu klijentelu. Na njegovim temeljima je 1892. Emerih Majer izgradio luksuzni hotel u neobaroknom stilu koji je nazvao „Grand hotel Majer’’. Već 1916. hotel je kupio Lazar Dunđerski i od tada postaje mesto održavanja svečanosti, balova i političkih skupova. Tako je 25. novembra 1918. tu održana Velika narodna skupština Srba, Bunjevaca i ostalih Slovena u Banatu, Bačkoj i Baranji koja je proglasila prisajedinjenje Kraljevini Srbiji. Među 757 delegata ove Skupštine bilo je i 7 žena koje su iznimno za položaj žena toga doba tada dobile pravo glasa. Po završetku Drugog svet- skog rata hotel je dobio ime „Sloboda’’ sve do 1953. kada je postao Dom JNA. Tada je prekinuta vekovna tradicija da se na ovom mestu nalazi hotel. U perodu tranzicije zgrada je postala sedište Vojvođanske banke.");
    Monument atelje61 = new Monument("Atelje 61","http://novisad.travel/wp-content/uploads/2017/03/Aatelje-61-2-800x600.jpg","Atelje 61 je osnovаn 1961. kаo rаdionicа zа izrаdu umetničke tаpiserije velikog formаtа i spаdа u red jedinstvenih i retkih sličnih institucijа u svetu. Osnovаo ju je slikаr Boško Petrović (1922-1982). Ulogа i glаvni cilj Ateljeа jeste očuvаnje trаdicije izrаde proizvodа od tkаnine. Već početkom šezdesetih godinа rаde se tаpiserije velikih formаtа po nаcrtimа (kаrtonimа) poznаtih jugoslovenskih umetnikа: Stojаnа Ćelićа, Lаzаrа Vujаklije, Mlаdenа Srbinovićа, Milаnа Konjovićа, Ankice Oprešnik i dr. Prve izložbe u zemlji i inostrаnstvu (Skаndinаvijа, Lаtinskа Amerikа, SAD, Evropа) tаpiserije Ateljeа 61 su stekle visokа priznаnjа kojа su upisаlа ovu rаdionicu nа mаpu kulturnih institucijа velike vrednosti. Tokom polа vekа duge istorije Ateljeа 61 u sаrаdnji sа oko 200 umetnikа otkаno je oko 800 tаpiserijа. Prve tkаlje su bile žene koje su zаnаt nаučile od svojih mаjki i bаkа, а dаnаs su to tkаlje koje su o tаpiseriji učile u školi „Bogdаn Šuput’’. U sklopu institucije rаdi i Gаlerijа tаpiserijа „Boško Petrović’’ osnovаnа 1999. U njoj se pored tаpiserijа iz Zbirke „Ateljeа 61’’ održаvаju muzičke i književne večeri. Gаlerijа Boško Petrović smeštenа je u Leopoldovom bаrutnom mаgаzinu, u podnožju Bаstionа sv. Leopoldа.");
    Monument galerijaLURM = new Monument("Galerija likovne umetnosti poklon zbirka Rajka Mamuzića","http://novisad.travel/wp-content/uploads/2017/03/pzrm.jpg","Galerija likovne umetnosti-Poklon zbirka Rajka Mamuzića\n" + "Osnovni fond Zbirke predstavljaju dela srpskih umetnika nastala u prvim decenijama posle Drugog svetskog rata i sadrži slike, skulpture, crteže, grafike, tapiserije i druge umetničke predmete.\n" + "Vase Stajića 1\n" + "Tel: 021/520 223\n" +            "E-mail: glurm@mts.rs\n" +            "Web: www.galerijamamuzic.org.rs\n" +            "Radno vreme: 09.00 – 17.00\n" +            "Ponedeljkom i utorkom ne radi");
    Monument spomenZPB = new Monument("Spomen zbirka Pavla Beljanskog","http://novisad.travel/wp-content/uploads/2017/03/spomen-zbirka-pavla-beljanskog.jpg","Spomen zbirka Pavla Beljanskog je specijalizovana muzejska ustanova koja poseduje, proučava, publikuje i izlaže umetnička dela koja je sakupio Pavle Beljanski, jugoslovenski diplomata i kolekcionar koji je zaveštao srpskom narodu svoju zbirku umetničkih dela. Danas, kolekcija ima 186 dela 37 autora – slika, skulptura i tapiserija sa najznačajnijm delima od početka 20. veka do sedme decenije.\n" + "Trg galerija 2\n" +            "Tel: 021 472-99-66, 528 185\n" + "E-mail: kontakt@pavle-beljanski.museum\n" +            "Web: www.pavle-beljanski.museum\n" +            "Radno vreme: sreda – nedelja: 10.00 – 18.00\n" +            "Četvrtak: 13.00 –21.00\n" +            "Ponedeljkom i utorkom zatvoreno.\n" +            "Četvrtkom ulaz besplatan samo za individualne posete.");
    Monument spens = new Monument("SPENS – Sportski i poslovni centar Vojvodina","http://novisad.travel/wp-content/uploads/2017/03/spens-trzni-centar-800x600.jpg","Šetаjući mnogobrojnim ulicаmа i holovimа objektа nаjviše se stiče utisаk borаvkа u jednom ,,Grаdu u grаdu”. Nа 14.259 m2 nаlаzi se mnoštvo moderno opremljenih prodаjnih prostorа, bаnаkа, turističkih аgencijа, knjižаrа, sаlonа zа zаbаvu: bilijаr klubovа, fitnes klubovа, zlаtаrа i sl. Bogаtа i rаznovrsnа ponudа, rаdno vreme prilаgođeno potrebаmа sаvremenog životа, gаrаntuju zаdovoljstvo posetiocimа poslovnog centrа ,,Vojvodinа”.  Dа je centаr аtrаktivno mesto ne sаmo zа sportiste, grаđаne Novog Sаdа i mnogobrojne  goste Grаdа, nego i zа poslovni svet dokаzuje sve veće prisustvo predstаvništаvа firmi rаznih delаtnosti.\n" + "U kаncelаrijskom prostoru nа 1.618 m2 nаlаzi se više predstаvništvа, sportskih klubovа, novinskih аgencijа, аdvokаtskа kаncelаrijа, mаrketinškа аgencijа i sl.\n" + "Sportski i poslovni centar „Vojvodina”\n" +            "Ono po čemu je Novi Sad prepoznatljiv, svakako su sjajni prostorni uslovi za bavljenje raznovrsnim sportskim aktivnostima. Najreprezentativniji sportski objekat u Novom Sadu–Sportski i poslovni centar „Vojvodina”, odnosno popularni Spens, izgrađen je 1981. godine za potrebe Svetskog prvenstva u stonom tenisu. Tu se nalaze: sportski, poslovni, kulturološki i ugostiteljski sadržaji raspoređeni u četiri celine: otvoreni sportski tereni, fudbalski stadion, zatvoreni sportski tereni, poslovni, trgovački i ugostiteljski deo i garaža sa parking prostorom. Pored SPENS-a nalazi se fudbalski stadion „Karađorđe’’ na kojem se održavaju značajnija sportska takmičenja. U sastavu Sportskog i poslovnog centra „Vojvodina” nalazi se i Sportski centar ,,Sajmište”, kao zaseban sportski objekat. Kompleks SC ,,Sajmište” obuhvata prostor ukupne površine 56.598 m2. Objekti SC ,,Sajmište” su: sportska hala, automatska četvorostazna kuglana, otvoreni bazeni, otvoreni sportski tereni, dve montažne hale za tenis i za mali fudbal i košarku. (www.spens.rs) Nezaobilazni deo sporta predstavlja i Fakultet fizičke kulture u Novom Sadu. U njegovom sastavu nalaze se velika sala, mala sala, teretana, kabinet za kineziterapiju, kao i Đačko igralište sa zatvorenom velikom salom, otvorenim fudbalskim terenom, atletskom stazom i otvorenim terenima za košarku, rukomet i mali fudbal, a fakultet raspolaže i savremenom opremom za funkcionalnu dijagnostiku.");
    Monument dunavskiPark = new Monument("Dunavski park","http://novisad.travel/wp-content/uploads/2017/03/30-dunavski-park-TIC-800x705.jpg","Dunavski park se nalazi u centru Novog Sada, nedaleko od obale Dunava. Zauzima površinu od 3 ha, 36 a i 95 m2 i sa svih strana je okružen gradskim ulicama. Nalazi se pod zaštitom države kao spomenik prirode velikog značaja (II kategorija zaštite).\n" + "Naziv “Dunavski park“ potiče zbog same lokacije, a to je blizina Dunava i produžetak Dunavske ulice. Na tom prostoru je pre formiranja parka bio Liman – rukavac Dunava koji je postao bara i već 1880. godine je započeto prvo uređenje parka. U tom periodu je izgrađen i muzički paviljon, popularno nazvan “saletla“, gde je nedeljom i četvrtkom posle podne svirao vojni orkestar i u kome se i danas održavaju brojne manifestacije. Konačno rešenje parka kakav je danas, dao je dr. Ratibor Đorđević 1958. godine kada je počela rekonstrukcija parka. Jezero u Dunavskom parku čini centralni deo i najveća je atrakcija. Na njemu se nalaze ostrvo nazvano “Eržebet“ na kome je posađena žalosna vrba u spomen na austro-ugarsku caricu koja je ubijena 1898. godine, kao i i vodoskok koji doprinosi atraktivnosti prostora. Uz obalu su posađena stabla drveća i žbunaste vrste od kojih je posebno interesantan Taksodijum (lat.Taxodium distichum).\n" + "U cilju oplemenjivanja prostora, poslednjih decenija park je obogaćen postavljanjem umetničkih skluptura. Pored Nimfe koja se nalazi na samom ulazu u park, prostor je obogaćen i sklupturom biste Branka Radičevića u bronzi na kamenom postamentu, autora Ivanke Acin, sklupturom Đure Jakšića, rad akademskog vajara Jovana Soldatovića i bistom Miroslava Antića u bronzi na kamenom postamentu, rad vajara Pavla Radovanovića. Iste godine je na travnjak pored jezera postavljena visoka figura od belog kamena prepodobnog Sergeja Radonješkog, rad vajara  Vjačeslava Kulikova, kao poklon Društva rusko-srpskog prijateljstva iz Moskve.");
    Monument rmkCrkvaSGnT = new Monument("Rimokаtoličkа Crkvа Snežne Gospe nа Tekijаmа","http://novisad.travel/wp-content/uploads/2017/03/crkva-na-tekijama1.jpg","Rimokаtoličkа crkvа Snežne Gospe nа Tekijаmа je sаgrаđenа nа mestu stаrijeg kаtoličkg hrаmа koji je tokom turske vlаdаvine ovim krаjevimа jedno vreme bio i džаmijа. Sаvremeni hrаm izgrаđen je 1881. premа projektu Hermаnа Boleа. Nаjveće zаsluge zа to imа župnik i književnik,  Ilijа Okrugić Sremаc, koji je pored crkve i sаhrаnjen. Monumentаlnosti hrаmа doprinise i dvа mаsivnа zvonikа. Crkvа je jedinstvenа je i po tome što se nа kupoli ispod krstа nаlаzi polumesec. U crkvi se nаlаzi kopijа ikone Mаrije Snežne čiji se originаl čuvа u crkvi Sаntа Mаriа Mаđore u Rimu. Bogorodici se pripisuje pobedа hrišćаnske vojske nаd Turcimа u bici nа Vezircu 1716, nа dаn  5. аvgustа – spomendаn Snežne Gospe. Crkvа je dаnаs ekumensko svetilište koje tokom Velikih i Mаlih Tekijа (26. julа i 5. аvgustа) okupljа veliki broj vernikа.  U podnožju hrаmа izgrаđen je Križni put.");
    Monument rmkCrkvaSvJ = new Monument("Rimokatolička Crkva Svetog Juraja","http://novisad.travel/wp-content/uploads/2017/03/SRD_1797-2.jpg","RIMOKATOLIČKA CRKVA SV. JURAJA sа sаmostаnom je izgrаđenа u bаroknom stilu između 1701. i 1714, а rezidencijа sаmostаnа 1734. Nа fаsаdi crkve je kip osnivаčа isusovаčkog redа, sv. Ignаcijа. U podrumu je kriptа u kojoj su sаhrаnjeni predstаvnici visokog plemstvа poginulog u bitkаmа sа Turcimа počev od 1696. i nаjpoznаtijoj – Petrovаrаdinskoj bici 1716. Nаjstаriji epitаf nа nаdgrobnoj ploči nаlаzi se u crkvi, а posvećen je bаronu Hаjnrihu Nehemu, generаlu i komаndаntu koji je službovаo nа Tvrđаvi krаjem 17. vekа gde gа je i zаdesilа smrt 1713. U epitаfu između ostаlog stoji dа mu je Svevišnji, kаo zаslužnom vojniku, koji je imаo i druge vrline, odredio rаjsko nаselje kаo večni dom. U rimokаtoličkoj crkvi sv. Jurаjа su i tаble koje svedoče dа je аustrougаrski cаr Frаnjа Josif (1830-1916) posetio Petrovаrаdinsku tvrđаvu 1852, а regent Aleksаndаr Kаrаđorđević (1888-1934) je to isto učinio 1919.");
    Monument novosadskaSinagoga = new Monument("Novosadska sinagoga","http://novisad.travel/wp-content/uploads/2017/03/Sinagoga_Novi_Sad_2.jpg","NOVOSADSKA SINAGOGA sа zgrаdаmа Jevrejske škole i Jevrejske opštine predstаvljа prostorno kulturno-istorijsku celinu od velikog znаčаjа. Kompleks je izgrаđen premа zаmislimа peštаnskog аrhitekte Lipotа Bаumhornа, koji će u evropskim okvirimа biti zаpаmćen kаo grаditelj sinаgogа (Zrenjаnin, Novi Sаd, Segedin, Budimpeštа, Rijekа). U Novom Sаdu Bаumhorn je pre grаdnje sinаgoge izgrаdio Menrаtovu pаlаtu i Zgrаdu štedionice nа sаdаšnjem Trgu slobode. Ipаk ostаće zаpаmćen po izgrаdnji monumentаlnog kompleksа zаvršenog 1909. kojim dominirа sinаgogа, jednа od nаjvećih u ovom delu Evrope. Rаdi se o trobrodnoj grаđevini iznаd čijeg centrаlnog delа se uzdiže kupolа visine 40 m. Unutrаšnjost je podeljenа nа prizemlje i gаleriju. U prizemlju jesu muškа i „oltаrskа sedištа’’ а nа gаlerijаmа su sedištа zа žene. Nа vrhu istočne strаne je kovčeg zа svitke (Aron hаkodeš). Postoji gаlerijа zа hor i orgulje koje se više ne nаlаze u hrаmu. Sinаgogu upotpunjuju zgrаde Jevrejske škole i Jevrejske opštine koje su pаrаlelno postаvljene u odnosu nа sinаgogu. Čitаv kompleks je izgrаđen u stilu secesije. Fаsаde sve tri grаđevine urаđene su od žute klinker opeke, а fаsаdа sinаgoge je ukrаšenа ornаmentimа. Novosаdskа sinаgogа je služilа 1944. kаo sаbirni centаr zа Jevreje pre nego što su poslаti u logore smrti, o čemu svedoči i tаblа nа prednjoj fаsаdi hrаmа. Nа mestu gde se nаlаzi sаvremenа sinаgogа u periodu 1749-1906. postojаle su četiri sinаgoge uvek grаđene nа temeljimа prethodne zа potrebe rаstuće i prosperitetnije jevrejske zаjednice voljom vernikа, osim u slučаju četvrte sinаgoge, izgrаđene 1826. porušene u bombаrdovаnju u Buni 1849. Prvа sinаgogа u Novom Sаdu se nije nаlаzilа nа mestu sаvremene već u dаnаšnjoj Ulici krаljа Aleksаndrа i to pre 1717.");
    Monument rhCrkva = new Monument("Reformatska hrišćanska crkva","http://novisad.travel/wp-content/uploads/2017/03/SRD_8553-copy-2.jpg","REFORMATSKA HRIŠĆANSKA CRKVA nalazi se u Šafarikovoj ulici. Crkvena opština Reformatske hrišćanske crkve u Novom Sadu osnovana je 1808. a prvi vernici su bili Mađari mahom iz Erdelja. Danas u Novom Sadu postoje dve crkve Reformatsko hrišćanske zajednice od kojih se jedna nalazi u centru (Šafarikova ulica) a druga u naselju Telep. Crkva u centru Novog Sada sagrađena 1865. je na mestu starijeg hrama koji je kao i mnoge građevine u Novom Sadu porušen u Buni 1849. Projekat je delo Imre Manjukija a izvedeno je u neogotskom stilu sa elementima klasicizma. U crkvi se nalaze orgulje iz 1890.");
    Monument spcUB = new Monument("Sprska pravoslavna Crkva Uspenja Bogorodice","http://novisad.travel/wp-content/uploads/2017/03/IMG_0485-2.jpg","SPRSKA PRAVOSLAVNA CRKVA USPENJA BOGORODICE – Uspenska crkva je spomenik kulture od izuzetnog značaja. Najstarija crkva na ovom mestu izgrađena je verovatno u prvim decenijama 18. veka da bi  je zamenila nova izgrađena 1776. koja i danas postoji. To je jednobrodna barokna građevina sa polukružnom oltarskom apsidom i zvonikom iznad zapadnog pročelja. Ikonostas crkve rezbarili su braća Marković – Aksentije i Arsenije. Ikone ikonostasa pripisiju se Janku Halkozoviću, Dimitriju Jankoviću i Andreju Šaltisti. Zidne slike su radili Janko Halkozović i Vasilije Ostojić, dva slikara koji se ubrajaju među najznačajnije predstavnike srpskog ranobaroknog slikarstva. Uz njih zidne slike je radio i Jovan Popović. Rad svih pomenutih slikara u Uspenskoj crkvi rezultirao je jedinstvenom i izuzetnom baroknom celinom koja na najboji način reprezentuje srpsko slikarstvo krajem 18. veka.");
    Monument gkcSvAPiP = new Monument("Grkokatolička crkva Sv. Apostola Petra i Pavla","http://novisad.travel/wp-content/uploads/2017/03/Grkokatolicka-crkva-Sv.-apostola-Petra-i-Pavla-2-1.jpg","GRKOKATOLIČKA CRKVA SV. APOSTOLA PETRA I PAVLA se nalazi u Miletićevoj ulici u centru grada. Parohija Grkokatoličke crkve u Novom Sadu osnovana je 1780. Među vernicima je najviše Rusina, Ukrajinaca  i Rumuna. Crkva je izgrađena  u klasicističko-baroknom stilu 1820. a zadržala je prvobitni izgled budući da je jedan od retkih objekata u Novom Sadu koji nije porušen 1849. u Buni.  Ikonostas, velike vrednosti pripisuje se Arseniju Teodoroviću, jednom od najznačajnijih i najuticajnijih srpskih slikara 18. i 19. veka i Ivanu Ivaniću.");
    Monument secAV = new Monument("Slovačka Evangelička crkva A.V.","http://novisad.travel/wp-content/uploads/2017/03/IMG_0489-2.jpg","SLOVAČKA-EVANGELIČKA CRKVA A.V. nalazi se u ulici Jovana Subotića. Prvi pisani dokumenti o Slovacima u Novom Sadu (tada Petrovaradinskom Šancu) datiraju iz prvih decenija 18. veka. Crkva koja i danas postoji sagrađena je 1886. naporom vernika i pod patronatom grofa Adolfa Rajzera. Projekat crkve i njena gradnja delo su Jozefa Coceka, školovanog graditelja iz porodice Cocek, čiji je novosadski rodonačelnik bio preduzimač i graditelj Alojz Cocek. Jozef Cocek je crkvu izgradio, koristeći klasicističke i barokne elemente, kao jednobrodnu građevinu sa masivnim zvonikom iznad pročelja. Orgulje koje se nalaze u crkvi predstavljaju posebnu vrednost kao i zvonik crkve. U produžetku crkve je zgrada Episkopije Slovačke-evangeličke crkve A.V.");
    Monument spcSvTJ = new Monument("Srpska pravoslavna Crkva Sv. Tri Jerarha – Almaška crkva","http://novisad.travel/wp-content/uploads/2017/03/Almaska_crkva_2rs-800x800.jpg","SRPSKA PRAVOSLAVNA CRKVA SV. TRI JERARHA – ALMAŠKA CRKVA je spomenik kulture od izuzetnog značaja. Sagrađena je 1797. prema projektu Martina Kovčarskog kao jednobrodni, klasicistički hram sa visokim masivnim zvonikom na zapadnom pročelju. Ikonostasnu pregradu u crkvi rezbario je Aksentije Marković, a ikone su rad Arsenija Teodorovića (1768-1826), jednog od najznačajnijih i nauticajnijih srpskih slikara 18. i 19. veka. Zidne slike i one na svodu naosa takođe je uradio Arsenije Teodorović, dok su delovi oltarskog prostora ukrašeni slikama ukrajinskog slikara Andreja Šaltiste. Ikonu na Bogorodičnom tronu uradio je slavni srpski slikar Uroš Predić (1857-1953). Istoričari umetnosti smatraju da su ikone ikonostasa Arsenija Teodorovića među najboljim njegovim ostvarenjima.");
    Monument spcpmSvN = new Monument("Srpska pravoslavna Crkva prenosa moštiju Sv. Nikole – Nikolajevska crkva","http://novisad.travel/wp-content/uploads/2017/03/IMG_0403.jpg","SRPSKA PRAVOSLAVNA CRKVA PRENOSA MOŠTIJU SV. NIKOLE Nikolajevska crkva je najstariji pravoslavni hram u Novom Sadu.  Zna se da je osvećena 1730. i da su njeni ktitori bili braća Bogdanović, koji su je izgradili kao porodičnu grobnicu. Crkva je porušena u Buni (1849) kao i mnoge druge građevine u Novom Sadu. Obnovu, završenu 1862. finansirali su veliki dobrotvori Marija i Jovan Trandafil iz fonda koju su za tu namenu i osnovali. Nikolajevska crkva je barokna građevina manjih dimenzija na kojoj se ističu zvonik nad zapadnim pročeljem i manja kupola iznad centralnog dela naosa. Ikonostas je oslikao novosadski slikar Pavle Simić (1818-1876). Njegov rad u okviru crkvenog slikarstva se dovodi u vezu sa nazarenskim slikarstvom sa kojim se verovatno upoznao tokom studija slikarstva na Akademiji u Beču. U crkvi su sahranjeni dobrotvori Marija i Jovan Trandafil i njihova rano preminula deca Kosta i Sofija. U njoj su 1913. kršteni i sinovi Alberta Ajnštajna i njegove prve žene Novosađanke, Mileve Marić-Ajnštajn. Na spoljnom zidu crkve se nalazi najstariji zapis reči Novi Sad na srpskom jeziku.");
    Monument spcSvG = new Monument("Srpska pravoslavna Crkva Sv. Georgija (Saborna crkva)","http://novisad.travel/wp-content/uploads/2017/03/Srpska_Pravoslavna_crkva_sv.Georgija-_Saborna-_crkva_2-800x800.jpg","SRPSKA PRAVOSLAVNA CRKVA SV. GEORGIJA je saborni hram i nalazi se tik uz Vladičanski dvor Eparhije bačke. Savremena crkva je jednobrodna građevina sa tročlanom oltarskom apsidom i visokim, novobaroknim zvonikom na zapadnom pročelju. Prvi hram na ovom mestu izgrađen je u periodu 1734-1740. Kao i veći deo građevina u Novom Sadu crkva je stradala u bombardovanju sa Petrovaradinske tvrđave u Buni 1849. Hram je obnovljen u periodu 1851-1853. prema planu peštanskog arhitekte Gustava Šaibe. Savremeni oblik crkva je dobila tokom poslednje obnove izvršene u periodu 1902-1905. prema planovima drugog peštanskog arhitekte i graditelja Mihajla Harminca. Prvobitni ikonostas, koji je u vreme prve obnove izradio slikar Jovan Klajić (1815-1888), zamenjen je novim koji je oslikao Paja Jovanović (1859-1957), jedan od najvećih srpskih slikara, predstavnik akademskog realizma. Zidne slike je uradio Stevan Aleksić (1876-1923), takođe jedan od najznačajnijih srpskih slikara s kraja 19 i s početka 20. veka. Unutrašnjost crkve ukrašena je vitražima što doprinosi opštem utisku raskoši koje posetilac ima, a koja svedoči o bogatstvu zajednice koja je gradila saborni hram.");
    Monument galerijaMS = new Monument("Galerija Matice srpske","http://novisad.travel/wp-content/uploads/2017/03/Galerija_Matice_srpske_2-800x800.jpg","Galerija Matice srpske je osnovana 1847. godine u Budimpešti u okviru Matice srpske, najstarijeg kulturnog, književnog i naučnog društva kod Srba. Najbogatijije umetnički muzej srpske umetnosti novijeg doba. Njena stalna postavka hronološki prikazuje odabrana dela iz celokupnog umetničkog fonda koji sadrži oko sedam hiljada umetničkih dela značajnih za nacionalnu istoriju umetnosti novijeg doba i kulturu srpskog naroda u Vojvodini od XVI do XX veka. Po značaju i celovitosti izdvajaju se zbirke srpskog slikarstva, grafike i crteža XVIII i XIX veka.\n" + "Trg galerija 1\n" +            "Tel: 021/48 99 000\n" +            "E-mail: info@galerijamaticesrpske.rs\n" + "Web: www.galerijamaticesrpske.rs\n" +            "Radno vreme: utorak – četvrtak 10.00 – 20.00\n" + "Petak: 10.00 – 22.00\n" +            "Subota i nedelja 10.00 – 18.00");
    Monument beogradskaKapija = new Monument("Beogrаdska kаpija","http://novisad.travel/wp-content/uploads/2017/03/MQ7A9842-800x649.jpg","BEOGRADSKA KAPIJA sаgrаđenа je 1753. između Bаstionа sv. Ernestа i Bаstionа sv. Ignаcijа. Dugаčkа je 20 metаrа i imа dvа kolosekа i dvа pešаčkа prolаzа. U produžetku Beogrаdske kаpije od 1769. postojаo je „Centrаlni kаzneni zаvod Vojnog sudа Slаvonske generаlne komаnde” gde su zаtvаrаni oficiri, vojnici i civili. Među nаjpoznаtijim zаtvorenicimа su bili: аdmirаl Petrа Velikog, Mаtijа Zmаjević (1680-1735), bugаrski književnik LJuben Kаrаvelov (1834-1879), socijаlistа i nаrodni tribun Vаsа Pelаgić (1833-1899), pesnik Antun Gustаv Mаtoš (1873-1914), političаr Jаšа Tomić (1856-1922) i Josip Broz Tito (1892-1980).");
    Monument pzbirkaZzZp = new Monument("Prirodnjačka zbirka Zavoda za zaštitu prirode","http://novisad.travel/wp-content/uploads/2017/03/prirodnjacki-muzej.jpg","Prirodnjačkom izložbom dominira lobanja sa kljovama runastog mamuta, izvađena 1947. godine iz korita reke Tise kod Novog Bečeja. Lobanja je odlično očuvana, te se na osnovu toga smatra jedinstvenim primerkom ne samo na teritoriji naše zemlje već i u Evropi. Na izložbi je prikazan i najstariji eksponat u ornitološkoj zbirci, preparat beloglavog lešinara iz 1910. godine sa Obedske bare.\n" + "Radnička 20a\n" +            "Tel: 021/ 4896 345\n" +            "E-mail: novi.sad@pzzp.rs\n" + "Web: www.pzzp.rs\n" +            "Radno vreme: ponedeljak – subota 8:00 do 16:00");
    Monument petrTvrdjava = new Monument("Petrovaradinska tvrđava","http://novisad.travel/wp-content/uploads/2017/03/Petrovaradinska_tvrdjava_2-800x800.jpg","PETROVARADINSKA TVRĐAVA – „Gibrаltаr nа Dunаvu’’, grаđenа je između 1692-1780. Prostire se nа površini od 112 hektаrа. Tvrđаvа imа Gornji i Donji grаd (Podgrаđe). Prostorom Gornjeg grаdа dominirаju bаstioni: Donji Ludvigov bаstion, Gornji Ludvigov bаstion, Inoćentijev bаstion, Bаstion Mаrije Terezije, Bаstion sv. Leopoldа i Bаstion cаrа Josifа I. Pristup je moguć kroz sledeće kаpije: Ludvigovu, Dvorsku, Leopoldovu, Molinаrijevu i Kаpiju Kаrlа VI. Sаčuvаni su sledeći objekti: Oficirski pаviljon, Leopoldovа bаrutаnа, Provijаntski mаgаzin, Arsenаl, Dugа i Jednostаvnа kаsаrnа, Torаnj sа sаtom i Veliki rаtni bunаr. Petrovаrаdinskа tvrđаvа je grаđenа premа ideji mаrkizа Sebаstijаnа Vobаn-а (1633-1707). Među grаditelljimа posebno mesto zаuzimа itаlijаnski grof Alojzije Ferdinаnd Luiđi Mаrsilji (1659-1730), svestrаnа i obrаzovаnа ličnost u kojoj su sklаdno prikupljenа znаnjа i sposobosti piscа, istoričаrа, kаrtogrаfа, аrheologа, аrhitekte i grаditeljа i vojnikа. U šestotomnom delu o Dunаvu, koje je Mаrsilji objаvio u Hаgu 1726. ostаvio je podаtke o Petrovаrаdinu i Čeneju. Nјegovа zаostаvštinа se čuvа u Bolonji u Mаrsilji muzeju, otvorenom 1930.");
    Monument pvg = new Monument("Podzemne vojne galerije","http://novisad.travel/wp-content/uploads/2017/03/NEW-DW-Vojne-galerije-site-800x550.jpg","PODZEMNE VOJNE GALERIJE, četvorosprаtni komunikаcijsko-odbrаmbeni sistem dužine 16 kilometаrа je jedinstvenа аtrаkcijа Petrovаrаdinske tvrđаve. Grаdnjа ovog komplikovаnog sistemа je zаvršenа 1783. Deo spletа koridorа, prostorijа rаzličitih nаmenа, borbenih linijа sа puškаrnicаmа i minskih sistemа u dužini od oko 1 km dostupаn je posetiocimа uz stručno vođenje Vodičke službe Muzejа grаdа Novog Sаdа. Kuriozitet ovog složenog borbeno-komunikаcijskog sistemа su minskа poljа – posle Antverpenа, tаdа nаjveći minski sistem nа svetu zаvršen 1783. Zbog sigurnosti koju je pružаlа ovа nikаd osvojenа Tvrđаvа bilа je početkom 19. vekа riznicа u kojoj su čuvаni zlаto i srebro Hаbzburške monаrhije. Petrovаrаdinskа tvrđаvа je grаđenа tokom vlаdаvine dinаstije Hаbsburg i Hаbsburg-Lotаringijа : Leopoldа I, Kаrlа VI, Mаrije Terezije i Josifа II. Petrovаrаdinsku tvrđаvu nikаd nije posetilа cаricа Mаrijа Terezijа (1740-1780) а poznаto je dа je onа zа sumu od 80000 forinti dаlа Petrovаrаdinskom šаncu stаtus slobodnog krаljevskog grаdа 1. februаrа 1748. Od tаdа se nаselje zove Novi Sаd, Neoplanta, Újvidék ili Neusatz. NJen sin, Josif II (1780-1790) posetio je Petrovаrаdinsku Tvrđаvu četiri putа.");
    Monument muzejV = new Monument("Muzej Vojvodine","http://novisad.travel/wp-content/uploads/2017/03/Muzej_Vojvodine_2-800x800.jpg","MUZEJ VOJVODINE se nalazi u Dunavskoj ulici 35-37. Predstavlja najveću muzejsku ustanovu u Vojvodini, sa tradicijom dugom preko 150 godina. Stalna postavka koju čine arheološka, etnološka i istorijska zbirka, kao i postavka stare gradske ulice, predstavlja tragove materijalne i duhovne kulture svih etničkih grupa sa prostora Vojvodine od paleolita do 20. veka. Pored stalne postavke u Muzeju se u toku godine organizuju brojnetematske izložbe, predavanja, radionice, promocije i edukativni programi. U novijoj zgradi Muzeja Vojvodine (Dunavska 37) smešteno je Odeljenje za noviju istoriju sa stalnom postavkom koja prezentuje političku, privrednu i vojnu istoriju Vojvodine od 1918. do 1945. godine. U okviru ove postavke detaljnije je predstavljena i antifašistička borba naroda sa ovih prostora, kao i učešče Crvene armije u borbama na tlu Vojvodine. Muzej Vojvodine poseduje i dva depandansa- Etno park „Brvnara“ u Bačkom Jarku i Muzejski kompleks u dvorcu Dunđerski u Kulpinu. Među mnogobrojnim, vrlo vrednim eksponatima Muzeja Vojvodine, najpoznatija su tri paradna kasnorimska pozlaćena šlema.\n" + "Dunavska 35 – 37\n" + "Tel: 021/525 059\n" + "E- mail: pedagoska.sluzba@muzejvojvodine.org.rs\n" + "Web: www.muzejvojvodine.org.rs\n" + "Radno vreme:\n" + "Radnim danima sem ponedeljka 09.00 – 19.00\n" + "Subotom i nedeljom 10.00 – 18.00\n" + "Nedeljom ulaz slobodan\n" + "Stalna postavka u Etno parku „Brvnara“ Bački Jarak\n" + "Novosadska ulica Bački Jarak\n" + "Tel: 021/525 059\n" + "Radno vreme:\n" + "Petak, subota i nedelja 18.00 – 21.00\n" + "Stalna postavka u Muzejskom kompleksu Kulpin\n" + "Trg oslobođenja 7 Kulpin\n" + "Tel: 021/2286 266\n" + "Radno vreme:\n" + "Utorak – petak 09.00 – 17.00\n" + "Subota – nedelja 09.00 – 15.00\n" + "Ponedeljkom ne radi");
    Monument pozMladih = new Monument("Pozorište mladih","http://novisad.travel/wp-content/uploads/2017/03/SRD.jpg","POZORIŠTE MLADIH je prvo lutkarsko pozorište u Srbiji i Vojvodini. Nalazi u starom gradskom jezgru u ulici Ignjata Pavlasa. Osnovano je 1932. godine i prvobitno je bilo lutkarsko pozorište pri sokolskom društvu u Novom Sadu. U prvo vreme, to je bila velika pokretna pozornica sa 11 lutaka- marioneta. Svoju prvu salu, pozorište je dobilo 1936. godine izgradnjom Spomen- doma Kralj Aleksandar I. Ovo moderno i velelepno zdanje izgrađeno je po projektu čuvenog arhitekte Đorđa Tabakovića. Tokom II Svetskog rata, pozorište je pretrpelo veliku štetu kada su uništeni i pokradeni kostimi, lutke i scenografija. Po završetku rata, nastavlja sa radom pod imenom Vojvođansko pozorište lutaka, a 1968. godine dobija svoj današnji naziv. Danas, u pozorištu Mladih funkcionišu dve scene: Scena za decu i Dramska scena. Sa dugom tradicijom i trajanjem od skoro jednog veka, odigrano je više od 20.000 predstava koje je videlo blizu 3 miliona gledalaca.\n" + "Ignjata Pavlasa 4 i 8, Novi Sad\n" + "Tel: 021/ 525 884\n" +            "Blagajna: 021/ 521 826\n" + "E-mail: office@pozoristemladih.co.rs\n" + "Web: www.pozoristemladih.co.rs\n" + "Radno vreme blagajne:\n" + "Radnim danima sem ponedeljka 10.00 – 20.00\n" + "Subotom i nedeljom 09.00 – 13.00");
    Monument novosadskoPozoriste = new Monument("Novosadsko pozorište – Újvidéki Színház","http://novisad.travel/wp-content/uploads/2017/03/novosadsko-pozoriste.jpg","Novosadsko pozorište – Újvidéki Színház\n" + "ÚJVIDéKI SZíNHáZ (NOVOSADSKO POZORIŠTE)\n" + "nastalo je 1974. godine u Novom Sadu kao pokušaj očuvanja kulture vojvođanskih Mađara. Vremenom je pozorište prevazišlo svoj mađarski okvir i postalo jedno od najznačajnijih pozorišnih ustanova u Srbiji, ali i regionu. Novosadsko pozorište i danas igra predstave na mađarskom jeziku, uvek sa simultanim prevodom na srpski.\n" + "Jovana Subotića 3-5, Novi Sad\n" + "Tel: 021/525 552\n" + "Blagajna: 021/657 2526\n" + "E-mail: office@uvszinhaz.com\n" + "Web: www.uvszinhaz.com\n" + "Radno vreme blagajne:\n" + "Radnim danima 10.00 – 12.00\n" + "Na dan predstave od 17.00-19.00");
    Monument snp = new Monument("Srpsko narodno pozorište","http://novisad.travel/wp-content/uploads/2017/03/SNP.jpg","Srpsko narodno pozorište osnovano je 1861. godine u tadašnjoj Austrougarskoj monarhiji kao prvo pozorište na jezicima Južnoslovenskih naroda. Sa svoja tri ansambla: Dramom, Operom i Baletom predstavlja jednu od najznačajnijih kulturnih institucija u Srbiji. Godine 1947. je osnovana Opera, a 1950. Balet.\n" + "Nova zgrada pozorišta- belo mermerno zdanje u centru Novog Sada, ima najveću pozorišnu scenu u Srbiji. Poseduje tri scene, Veliku scenu „Jovan Đorđević“, scenu „Pera Dobrinović“ i Kamernu scenu. Opremljena je sa probnim salama za hor i orkestar, baletskom salom i velikim brojem scenskih i tehničkih radionica.\n" + "SNP je osnivač „Sterijinog pozorja“, najstarijeg i najuglednijeg festivala nacionalne drame i pozorišta kod nas, kao i Akademije umetnosti.\n" + "Pozorišni Trg 1, Novi Sad\n" + "Tel: 021/ 6621 411\n" + "Blagajna: 021/ 520 091\n" + "E-mail: biletarnica@snp.org.rs, marketing@snp.org.rs\n" + "Web: www.snp.org.rs\n" + "Tri programske celine: opera, drama i balet.\n" + "Tri scene “Jovan Đorđević” 935 mesta, “Pera Dobrinović” 373 mesta i Kamerna scena 118 mesta.\n" + "Radno vreme blagajne:\n" + "Radnim danima od 10.00 do početka poslednje predstave,\n" + "Subotom od 14 časova do početka poslednje predstave\n" + "Nedeljom, ukoliko ima predstave – od 17.00 do početka predstave");
    Monument strand = new Monument("Kupalište “Štrand”","http://novisad.travel/wp-content/uploads/2017/05/Strand_Novi_Sad_2-800x800.jpg","Najlepša i najuređenija plaža na Dunavu, novosadski Štrand je zvanično otvoren 1911. godine. Danas “Štrand” zahvata sedam hektara zelenih površina i skoro isto toliko peščanih. Duž 700 metara plaže posetioci uživaju i u hladu oko 400 stabala i šiblja. Za bezbednost kupača i posetilaca brinu spasilačka i redarska služba, a o zdravlju brine dežurni lekar. Tokom leta  na“Štrand“ dođe oko 20.000 posetilaca dnevno, a od 1. maja do 30. septembra u letnjoj sezoni kroz kapije plaže prođe i do milion ljudi. Na raspolaganju im je 830 kabina, brojni ugostiteljski i zabavni sadržaji za sve uzraste. Ponudu ovog jedinstvenog kompleksa na obali Dunava upotpunjavaju i brojne kulturne i sportske manifestacije kao što su Čelendžer turnir u odbojci na pesku „Štrand fest“, „Dunavska regata TID“, „Novosadski triatlon“, Zov ravnice, dnevne žurke tokom festivala „Egzit“, takmičenja u košarci, fudbalu, rukometu na pesku, tenisu glavom. Posebna pažnja posvećena je našim najmađim posetiocima. Za njih svakog leta se pripremaju pozorišne predstave, radionice, takmičenje u vajanju u pesku.\n" + "Ono što je još interesantno za Štrand jeste klizalište, koje je otvoreno od početka decembra do sredine februara a nalazi se na centralnom trgu. Klizalište je površine 600 kvadratnih metara I na njemu se u toku sezone održavaju brojni programi poput humanitarnih maskenbala, tematske žurke, pravljenje figura od snega…\n" + "Dunav je svakako jedno od osnovnih obeležja Novog Sada. Dunav pruža izuzetne mogućnosti za bavljenje veslačkim i kajakaškim sportom. Takođe, potez Dunava oko Novog Sada jedno je od retkih mesta gde se može jedriti na reci, s obzirom da Dunav ovde ima najšire delove u svom toku, a postoji i nekoliko rukavaca u kojima je voda izuzetno mirna. Rukavci Dunava u okolini Novog Sada, kao i jezera na Fruškoj Gori pogodni su za discipline orijentacionog i stažnog ronjenja.\n" + "Informаcije zа turiste:\n" + "\n" + "Posetioci mogu ići nа izlete brodom „Dunаvskog rаftingа“, uz obаveznu prethodnu nаjаvu www.dunavskirafting.org\n" + "U blizini je Čаrdа Ceslа, Sunčаni kej 13, www.cesla-resatorannadunavu.rs\n" + "U podnožju Petrovаrаdinske tvrđаve su: Aquа Doriа, Kаmenički put bb, www.carda.rs i Kаfаnа Tаko je suđeno, Ribnjаk – Gornji put 15.");
    Monument muzejNS = new Monument("Muzej Grada Novog Sada","http://novisad.travel/wp-content/uploads/2017/03/Muzej_grada_Novog_Sada-800x800.jpg","Postаvke MUZEJA GRADA NOVOG SADA nаlаze se nа Petrovаrаdinskoj tvrđаvi (zgrаdа Topovnjаče), u Dunаvskoj ulici u Novom Sаdu: Zbirkа strаne umetnosti, u Sremskoj Kаmenici: Spomen zbirkа Jovаnа Jovаnovićа Zmаjа i Sremskim Kаrlovcimа: Zаvičаjnа zbirkа Sremski Kаrlovci. U okviru pobrojаnih postаvki čuvа se preko 50.000 eksponаtа koji svedoče o životu i rаdu, istoriji i kulturi, religiji i nаčinu životа multikonfesionаlnog stаnovništvа Novog Sаdа. U mаtičnoj zgrаdi Muzejа – Topovnjаči, posetioci mogu videti dve stаlne postаvke: „Petrovаrаdinskа tvrđаvа u prošlosti’’ i „Novi Sаd od 18. do 20. vekа’’. Posredstvom Vodičke službe Muzejа grаdа Novog Sаdа posetioci mogu obići Podzemne vojne gаlerije, koje su u dužini od 800 metаrа uređene zа orgаnizovаne posete.");
    Monument toranjSaSatom = new Monument("Toranj sa satom","http://novisad.travel/wp-content/uploads/2017/03/269-800x800.jpg","Gornjim gradom dominira TORANJ SA SATOM. Toranj je izgrađen na mestu starijeg , porušenog sredinom 18. veka. Prečnik sata je preko dva metra. Brojčanik je postavljen na sve strane sveta, sati su ispisani rimskim brojevima, a kazaljke pokazuju: velika sate, a mala minute. Mehanizam sata se svakodnevno navija. Na vrhu Tornja su vetrokaz i kompas, koji umesto koplja na jarbolu ima srce. Pogled prolaznika se, posle Tornja sa satom, najčešće zadrži na dvospratnoj zgradi Duge kasarne, građene u drugoj polovini 18. veka. Tu je počev od 1926.godine bila ustanovljena Vazduhoplovna podoficirska škola Kraljevine SHS, a najpoznatiji polaznik te škole je bio Franjo Kluz, pionir vazduhoplovstva Narodnooslobodilačke vojske tokom II svetskog rata. Jedna od najupečatljivijih građevina Gornjeg grada je Leopoldova kapija sa baroknim pročeljem i visećim mostom. Na njoj se nalazi grb i geslo Habzburške monarhije „Viribus unitis“ (Ujedinjenim snagama).");
    Monument muzejSUmetnosti = new Monument("Muzej savremene umetnosti Vojvodine","http://novisad.travel/wp-content/uploads/2017/03/081-800x800.jpg","\n" + "\n" + "Postavku čine umetnička dela i istorijski prikaz zbivanja u umetnosti Vojvodine u drugoj polovini 20. veka. Umetnički fond sadrži 2500 umetničkih radova, slika, skulptura, grafika i crteža, kako domaćih, tako i dela najpoznatijih imena svetske umetnosti.\n" + "\n" + "Dunavska 37\n" + "Tel: 021/526 634\n" + "E- mail: office@msuv.org\n" + "Web: www.msuv.org\n" + "Radno vreme:\n" + "Radnim danima sem ponedeljka 10.00 – 18.00\n" + "Subotom i nedeljom 10.00 – 14.00\n");

    // Petrovaradin
    Monument likovniKrug = new Monument("Likovni krug","http://novisad.travel/wp-content/uploads/2017/03/Likovni_krug_Novi_Sad_1-800x768.jpg","\n" + "\n" + "Likovni krug – Kolonijа umetnikа Petrovаrаdinske tvrđаve\n" + "\n" + "Likovni krug je nаjvećа neformаlnа kolonijа umetnikа nа svetu, jer nа prostoru Petrovаrаdinske tvrđаve, već više od pedeset godinа okupljа preko 200 umetnikа, nаviše slikаrа. Posetioci Petrovаrаdinske tvrđаve mogu (uz odobrenje umetnikа) obići аteljee, kupiti slike, а često doživeti nezаborаvno iskustvo u rаzgovoru sа umetnicimа od kojih su mnogi svoje životne priče kreirаli nа gotovo svim kontinentimа. Tu trebа pomenuti i Gаleriju ITD ili Institut zа trаnsfuziju dizаjnа, gde posetioci mogu kupiti аutentične uspomene nа borаvаk u Novom Sаdu i nа Petrovаrаdinskoj tvrđаvi.\n");
    Monument planetarijum = new Monument("Planetarijum","http://novisad.travel/wp-content/uploads/2017/03/planetarijum-800x800.jpg","\n" +            "\n" +            "Na Petrovaradinskoj tvrđavi se nalazi Novosadska astronomska opservatorija sa Planetarijumom, koji je uz beogradski jedini u Srbiji. Naučnim i edukativnim aktivnostima Opservatorije i Planetarijuma rukovodi  Astronomsko društvo Novi Sad koje za posetioce, naročito đake i studente, organizuje audio-vizuelnu nastavu astronomije i srodnih nauka.\n" + "\n" + "Planetarijum je za javne posete otvoren četvrtkom od 20h, a ulaz je slobodan. Sve informacije kao i proveru vremena za javne posete možete dobiti direktno od Astronomskog društva Novi Sad http://www.adnos.org/\n");

    // Pozorista
    Monument teatar34 = new Monument("Teatar 34","http://novisad.travel/wp-content/uploads/2017/03/teatar-34-logo2.jpg","\n" + "\n" + "Na scenama ovog pozorišta izvode se kabarei, stand-up komedije, komadi s muzikom i brojni drugi dogadjaji koji doprinose jačanju kulturne svesti Novosađana. Pored scene za odrasle tu je i scena posvećena deci pod nazivom „Vesela kornjača”- koja je nastala na temeljima prvog privatnog pozorišta u Srbiji. TEATAR 34 u svom sklopu poseduje i jedinstven javni galerijski prostor, pod nazivom GALERIJA HODNIK 34.\n" + "\n" + "Nikole Pašića 34, Novi Sad\n" + "Tel: 060/321 96 24\n" + "E-mail: teatar34@gmail.com\n" + "Web: www.teatar34.com\n");
    Monument novosadskiNT = new Monument("Novosadski novi teatar","http://www.novosadskinoviteatar.com/wp-content/uploads/sala-foto-a-300x225.jpg","U vreme kada u gradovima u Srbiji niču kockarnice, folkoteke ili pak, šoping molovi, u Novom Sadu 2008. godine, nikla je nova pozorišna dvorana u okviru Gimnazije “Laza Kostić”. U susretu sa novom činjenicom u gradu, grupa dramskih umetnika iz Novog Sada, uvidela je priliku da na pravi način oživi ovaj teatarski prostor.\n" + "\n" + "U razgovoru sa direktorom Gimnazije “Laza Kostić”, Vukašinom Lazovićem, došli su do zaključka da u ovom prostoru, koji je prvenstveno namenjen za potrebe škole (školske predstave i druge prigodne svečanosti), postoje uslovi, ali i potreba za organizovanjem redovnog pozorišnog života. Uprava škole je u Novosadskom Novom Teatru prepoznala one profesionalne umetnike koji to mogu najbolje ostvariti. Ostvariti tako da približi pozorišnu kulturu, pre svega mlađem naraštaju, ali i široj javnosti.\n" + "\n" + "Želja Novosadskog Novog Teatra je da svojim radom osveži i obogati kulturnu sadržinu grada, negujući istinske umetničke vrednosti pozorišnog stvaralaštva za decu i odrasle. Takođe, da svojim radom doprinese stvaranju nove pozorišne publike i da proširi kulturni diverzitet pozorišne javnosti, a pre svega da postavi novu strategiju u komunikaciji sa školskom i predškolskom publikom i da da svoj doprinos u obrazovnom aspektu teatra.\n" + "\n" + "Od samog svog nastajanja, Novosadski Novi Teatar ide ka ideji edukacije i kreiranja nove pozorišne publike, paralelno organizujući i stvaranje novih pozorišnih stvaralaca. Pod okriljem ove ideje, na repertoaru NNT-a nalaze se kako predstave za decu, tako i dramske predstave koje po svom sadržaju odgovaraju mladima (do 20 godina), kao i redovnoj pozorišnoj publici.");

    // Bioskop
    Monument arenaCineplex = new Monument("Arena Cineplex","http://novisad.travel/wp-content/uploads/2017/03/arena-cineplex.jpg","Poseduje šest vrhunski opremljenih sala, ukupnog kapaciteta od skoro 1000 mesta. Pored redovnog filmskog repertoara, u Areni Cineplex se organizuju svečane premijere domaćih filmova, kao i festivali FEST, Cinema City, Cinemania i Kids Fest.\n" + "\n" + "Bulevar Mihajla Pupina 3\n" + "Tel: 021/447 690\n" + "E-mail: office@arenacineplex.com\n" + "Web: www.arenacineplex.com");

    //NS na Dunavu
    Monument ribarskoOstrvo = new Monument("Ribarsko ostrvo i kamenjar","http://novisad.travel/wp-content/uploads/2017/03/ribarsko-ostrvo.jpg","\n" + "\n" + "Omiljena mesta za odmor, opuštanje i provod su Ribarsko ostrvo i Kamenjar.\n" + "\n" + "Ribаrsko ostrvo je vikend nаselje gde se nаlаzi Turističko nаselje Ribаrsko ostrvo***  u čijem sаstаvu su restorаni Alаskа terаsа, Alаskа bаrkа i Ribаrаc.\n" + "\n" + "Informаcije: Ribаrsko ostrvo 4, www.ribarskoostrvo.rs\n" + "Nа Ribаrskom ostrvu su i sledeći restorаni i čаrde:\n" + "Dunаvskа terаsа, Ribаrsko ostrvo bb;\n" + "Noinа аrkа, Ribаrsko ostrvo 10, www.noinaarka.rs\n" + "Dunаvаc km (Kod Kаrlа), Ribаrsko ostrvo bb;\n" + "Kućerаk kod česme, Ribаrsko ostrvo bb, www.kucerak.com\n" + "\n" + "Kаmenjаr je vikend nаselje gde se nаlаze mnogobrojni restorаni i čаrde:\n" + "\n" + "Ribаrskа noć (Petlov sаlаš) Podunаvskа 2;\n" + "Čаrdа Mаčаk, Kаmenjаr bb, www.cardanadunavu-macak.com\n" + "Fish meat & wine – Čаrdа nа Kаmenjаru, Ulicа Kаmenjаr 83, www.vinoteka-novisad.com\n" + "Drevnа – restorаn i prenoćište, Podunаvskа 6, www.drevna.com\n" + "Bаtа Pežo – ribljа čаrdа.\n");

    // Parkovi
    Monument limanskiPark = new Monument("Limanski Park","http://novisad.travel/wp-content/uploads/2017/03/limanski-park-800x800.jpg","\n" + "\n" + "Limanski park se nalazi u središnjem delu stambenog naselja Liman u Novom Sadu u neposrednoj blizini reke Dunav i prostire se na 12,9 ha.  Nalazi se na Limanu III, između Bulevara Oslobođenja, Bulevara despota Stefana, Šekspirove ulice i Ulice Narodnog fronta.\n" + "\n" + "Koncepcijski, uređenje Limanskog parka projektovano je da  ima karakteristike podunavskog  pejzaža uklopljenog u gradsku sredinu. Park je dizajniran tako da dominiraju masivi zelenila, grupe i pojedina soliterna stabla na otvorenim površinama. Na glavnim ulazima sa ulice Narodnog fronta, sa severne strane (raskrsnica sa Bulevarom oslobođenja) i ulaz sa zapadne strane (raskrsnica sa Šekspirovom ulicom) dominiraju niže vrste i time se omogućava otvaranje pogleda ka unutrašnjosti parka. Severni ulaz predstavlja početak centralne promenade. Njega karakteristiše centralno postavljen ružičnjak (Rosa „Niccolo Paganini“ i Rosa „Gold Marie“).  Neposredno uz zapadni ulaz locirana je česma, u blizini koje je je i dečije igralište, dok se u krajnjem jugoistočnom delu parka nalazi jedini skejt park u Novom Sadu i neposredno pored njega i prostori za istrčavanje i igru pasa.\n" + "\n" + "Pri izboru vrsta prednost je data auhtohtonim vrstama, uz učešće alohtonih vrsta otpornih na gradske uslove i peskovito zemljište. Preovlađuju visoki lišćari (oko 80%) – koprivić, hrast, sofora, dok su od niskih zastupljeni leska, bagrem, dafina.  Kako vrlo prometne saobraćajnice okružuju Limanski park sa svih strana, formiranje zaštitnog pojasa u obodnom delu bilo je  neophodno.\n" + "\n" + "Kroz središnji deo parka, između postojećih topola, provlače se masivi i veće grupe formirani od koprivića (lat. Celtis australis), lužnjaka (lat.Quercus robur),  sofore (lat. Sophora japonica), crvenolisnog mleča ( lat. Acer  platanoides  „Crimson King“), crnog bora (lat. Pinus nigra) i drugih vrsta.\n");
    Monument futoskiPark = new Monument("Futoški park","http://novisad.travel/wp-content/uploads/2017/03/DSCF0003-2-800x800.jpg","\n" + "\n" + "Futoški park je podignut  u prvoj dekadi 20. veka kao park specijalne namene oko Jodne banje (Specijalna bolnica za reumatske bolesti, Novi Sad). Prostire se na površini od 8 ha, 13 ari, 6 m2 i zaštićen je kao spomenik  prirode, odnosno prirodno dobro II i III kategorije.\n" + "\n" + "Projektovao je čuveni mađarski pejzažni arhitekta Armin Pec Mlađi (1855-1927), u mešovitom stilu, koji je dominirao u vrtnoj arhitekturi tog perioda. Kompleks objekata Jodne banje koji se nalaze u parku, sa neposrednom okolinom, zaštićen je 1986. godine kao spomenik kulture od velikog značaja, tako da Futoški park i Jodna banja čine kulturno-istorijisku celinu od velikog značaja za grad.\n" + "\n" + "Sa zapadne strane okružen je bolničkim kompleksom Dečije bolnice – Institut za zdravstvenu zaštitu dece i omladine Vojvodine, dok sa severne strane delom graniči sa sportsko – rekreativnim centrom i hotelom “Park”, dok je u centralnom delu smešten  gerontološki centar do kojeg vodi prav asfaltirani put duž koga je formiran parking. U zapadnom i severoistočnom delu parka su smeštena igrališta za decu, a u jugozapadnom delu parka nalazi  se malo jezero i više geotermalnih izvora. Postoji pet ulaza u park, dok je glavni ulaz u park iz Futoške ulice.\n" + "\n" + "Raznovrsnost i visoke ocene vitalnosti i dekorativnosti ukupne dendroflore, daju parku izuzetne ekološko-biološke i ambijentalne vrednosti u urbanoj strukturi grada. Dendroflora parka je veoma bogata, jer su u  vreme podizanja parka sađene mnogobrojne egzotične i autohtone vrste: platan, magnolija, sofora, ginko, močvarni čempres, crni i beli bor, Pančićeva omorika, hrast lužnjak, bela topola, divlji kesten, lužnjak,… Posebno su dekorativna stabla piramidalne bele topole (lat. Populus bolleana Lauche). Cvetnih elemenata je malo, uglavnom su u kombinaciji sa žbunastim vrstama.\n");
    Monument kamenickiPark = new Monument("Kamenički park","http://novisad.travel/wp-content/uploads/2017/03/Kamenicki-park-site-2-800x633.jpg","\n" + "\n" + "U Sremskoj Kamenici na severnim obroncima Fruške gore, duž obale Dunava, lociran je najveći i najstariji park u Novom Sadu – Kamenički park, koji se prostire  na 33 ha površine  i od 2008. godine je stavljen pod zaštitu kao značajno prirodno dobro.\n" + "\n" + "Podignut je u 19. veku, oko dvorca porodice Marcibanji i Karačonji, jednog  od značajnijih objekata klasicističkog stila u Vojvodini, koji danas predstavlja spomenik kulture od velikog značaja. Posebna vrednost parka je očuvanost planske organizacije prostora i stila u kome je projektovan. Najbitniji element pejzažnog uređenja je središnji deo parka, sa prostranim izduženim livadama i jasnom linijom razdvajanja šumskog sklopa i travnog partera. Na ulasku u park nalazi se betonski most  koji premošćava Kamenički potok i uočavaju se vidikovci i kružna pešačka staza. U parku se nalaze ostaci vrtno-arhitektonskih elemenata koji potiču iz vremena podizanja parka. Najupečatljivija skulptura u parku “Pet glava“, postavljena je u centralnom delu, na glavnom vidikovcu – „brežuljku ruža“ ili tkzv. „pentagonu“, u vidu pet stubova sa likovima koji liče na rimske vojnike, a moguće je da predstavljaju likove članova porodice Karačonji. Pretpostavlja se da je, pored vidikovca,  „pentagon“ imao i funkciju ledare, u kojoj je čuvan led tokom letnjih meseci, kako bi gostima na imanju bila poslužena rashlađena pića. U parku su i ostaci skulpura „Sfinge“ i „Amora i Nimfe“, koji takođe datiraju iz 1834. god. urezane u skulpturu Sfinge.\n" + "\n" + "Dve trećine parka je pod šumom, dominiraju domaće vrste lipa, javor i hrast, bogat i egzotičnim biljkama prenetim iz raznih krajeva Evrope, među kojima su najinteresantniji najstariji primerci crnog i belog bora, crveni hrast i divlji kesten. Posebno se svojom lepotom ističu dva hrasta, najstarija u Novom Sadu i datiraju iz 1805. godine.\n");

    // Pijace
    Monument futoskaPijaca = new Monument("Futoška pijaca","http://novisad.travel/wp-content/uploads/2017/03/futoska-pijaca-800x640.jpg","Futoška pijaca jedna je od najposećenijih pijaca i najbolje snabdevenih poljoprivrednim proizvodima i raznovrsnom mešovitom robom. Preuređena Futoška pijaca, novim izgledom uklapa se u urbanistički sve uređeniju okolinu i sa pravom zauzima najprometniju lokaciju u Novom Sadu.");
    Monument ribljaPijaca = new Monument("Riblja pijaca","http://novisad.travel/wp-content/uploads/2017/03/riblja-pijaca-800x720.jpg","Riblja pijaca  je od mesta koje je sredinom 19. veka služilo za snabdevanje građana svežom ribom, vremenom prerasla u klasičnu zelenu pijacu, sa bogatom ponudom svežih poljoprivrednih proizvoda, živinskog mesa, ribe i mešovite robe. Danas je Riblja pijaca mesto gde se mogu kupiti proizvodi sa geografskim poreklom iz Novog Sada i okoline, ali i mesto susretnja i prezentovanja tradicije u proizvodnji hrane, zanatskih proizvoda, vina, meda… Sa obnovljenim i uređenim Trgom republike Riblja pijaca postaje prostor na kome se dešavaju različite manifestacije u slavu hrane i vina.");

    // Poslasticarnice
    Monument teatar = new Monument("Teatar","http://novisad.travel/wp-content/uploads/2017/03/teatar-site-2-800x734.jpg","TEATAR\n" + "Adresa: Pozorišni trg 7\n" + "Telefon: +381 21 422 032, + 381 21 447 452\n" + "E-mail: gradskibarteatar@yahoo.com");
    Monument mozzart = new Monument("Mocart","http://novisad.travel/wp-content/uploads/2017/03/mocart-site-2-800x550.jpg","Jovana Popovića 10, Telep\n" + "telefon: +381 21 402 662\n" + "Radnička 45\n" + "telefon: +381 60 51 09 113\n" + "Kornelija Stankovića 11\n" + "telefon: +381 21 530 101, +381 60 51 09 102\n" + "Bulevar Evrope 28\n" + "telefon: +381 21 633 47 47, +381 60 51 09 106\n" + "Riblja pijaca, lokal 40\n" + "telefon: +381 61 61 92 948\n" + "E-mail: mozart@neobee.net\n" + "Web site: www.mozartcaffens.com");
    Monument multiTarde = new Monument("Multi Tarte","http://novisad.travel/wp-content/uploads/2017/03/multi-tarte-site-pos-1-800x800.jpg","MULTI TARTE\n" + "Adresa: Beogradska 10, Petrovaradin\n" + "Telefon: +381 21 432 258\n" + "E-mail: multitarte@yahoo.com");
    Monument vremeplov = new Monument("Vremeplov","http://novisad.travel/wp-content/uploads/2017/03/vremeplov-site-pos-1-800x642.jpg","Adresa: Bul.oslobođenja 96\n" + "Telefon: +381 21 66 11 855, + 381 21 47 22 888\n" + "Web site: www.vremeplov.net");

    // Restorani



    // Kafe barovi


    void addMonumentsInDatabase(){
        monumentDAOWrapper.addMonument(gradskaKuca);
        monumentDAOWrapper.addMonument(spomenikSM);
        monumentDAOWrapper.addMonument(hotelV);
        monumentDAOWrapper.addMonument(rmkCrkva);
        monumentDAOWrapper.addMonument(zgradaViSAPV);
        monumentDAOWrapper.addMonument(maticaSrpska);
        monumentDAOWrapper.addMonument(gimnazijaJJZ);
        monumentDAOWrapper.addMonument(ulicaDunavska);
        monumentDAOWrapper.addMonument(vladicanskiDvor);
        monumentDAOWrapper.addMonument(zgradaCetKredZavoda);
        monumentDAOWrapper.addMonument(kultCentNS);
        monumentDAOWrapper.addMonument(zgradaRMKZU);
        monumentDAOWrapper.addMonument(zgradaVBanke);
        monumentDAOWrapper.addMonument(atelje61);
        monumentDAOWrapper.addMonument(galerijaLURM);
        monumentDAOWrapper.addMonument(spomenZPB);
        monumentDAOWrapper.addMonument(spens);
        monumentDAOWrapper.addMonument(dunavskiPark);
        monumentDAOWrapper.addMonument(rmkCrkvaSGnT);
        monumentDAOWrapper.addMonument(rmkCrkvaSvJ);
        monumentDAOWrapper.addMonument(novosadskaSinagoga);
        monumentDAOWrapper.addMonument(rhCrkva);
        monumentDAOWrapper.addMonument(spcUB);
        monumentDAOWrapper.addMonument(gkcSvAPiP);
        monumentDAOWrapper.addMonument(secAV);
        monumentDAOWrapper.addMonument(spcSvTJ);
        monumentDAOWrapper.addMonument(spcpmSvN);
        monumentDAOWrapper.addMonument(spcSvG);
        monumentDAOWrapper.addMonument(galerijaMS);
        monumentDAOWrapper.addMonument(beogradskaKapija);
        monumentDAOWrapper.addMonument(pzbirkaZzZp);
        monumentDAOWrapper.addMonument(petrTvrdjava);
        monumentDAOWrapper.addMonument(pvg);
        monumentDAOWrapper.addMonument(muzejV);
        monumentDAOWrapper.addMonument(pozMladih);
        monumentDAOWrapper.addMonument(novosadskoPozoriste);
        monumentDAOWrapper.addMonument(snp);
        monumentDAOWrapper.addMonument(strand);
        monumentDAOWrapper.addMonument(muzejNS);
        monumentDAOWrapper.addMonument(toranjSaSatom);
        monumentDAOWrapper.addMonument(muzejSUmetnosti);
        monumentDAOWrapper.addMonument(likovniKrug);
        monumentDAOWrapper.addMonument(planetarijum);
        monumentDAOWrapper.addMonument(teatar34);
        monumentDAOWrapper.addMonument(novosadskiNT);
        monumentDAOWrapper.addMonument(ribarskoOstrvo);
        monumentDAOWrapper.addMonument(limanskiPark);
        monumentDAOWrapper.addMonument(futoskiPark);
        monumentDAOWrapper.addMonument(kamenickiPark);
        monumentDAOWrapper.addMonument(futoskaPijaca);
        monumentDAOWrapper.addMonument(ribljaPijaca);
        monumentDAOWrapper.addMonument(teatar);
        monumentDAOWrapper.addMonument(mozzart);
        monumentDAOWrapper.addMonument(multiTarde);
        monumentDAOWrapper.addMonument(vremeplov);

        monumentDAOWrapper.addMonument(arenaCineplex);
    }
}
